import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkOnly } from 'workbox-strategies';
import { BackgroundSyncPlugin } from 'workbox-background-sync';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Background Sync for the Triage API
const bgSyncPlugin = new BackgroundSyncPlugin('emergency-alerts-queue', {
  maxRetentionTime: 24 * 60 // Retry for up to 24 hours
});

registerRoute(
  ({ request, url }) => request.method === 'POST' && url.pathname.endsWith('/triage'),
  new NetworkOnly({
    plugins: [bgSyncPlugin]
  }),
  'POST'
);

self.addEventListener('install', () => self.skipWaiting());
self.addEventListener('activate', () => self.clients.claim());
